version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    networks:
      - mynetwork
    depends_on:
      - redis
  redis:
    image: redis:latest
    networks:
      - mynetwork
    ports:
      - "6379:6379"
networks:
  mynetwork:
    driver: bridge
